namespace DeskAI.App.Help;

/// <summary>
/// Every "?" explanation in DeskAI, in one place.
/// </summary>
/// <remarks>
/// <para>
/// Kept in one list rather than typed into each page so the rules for help text can be
/// tested: all three parts present, short enough to read at a glance, and free of the
/// technical words the main interface keeps out. Pages refer to a topic by its ID, and a test
/// scans the pages so a mistyped ID fails the tests instead of showing an empty pop-up.
/// </para>
/// <para>
/// Every sentence here must stay true. If a feature changes, its explanation changes in the
/// same commit; a help text that promises more than the app does is worse than none.
/// </para>
/// </remarks>
public static class HelpCatalog
{
    public const int MaxWhatItIsWords = 20;
    public const int MaxWhatItDoesWords = 40;
    public const int MaxWhatItNeverDoesWords = 25;

    /// <summary>Words the main interface keeps out, per the project's user-experience rules.</summary>
    public static IReadOnlyList<string> BannedWords { get; } =
    [
        "metadata", "endpoint", "provider", "schema", "sqlite", "deterministic", "authorization",
        "authorize", "telemetry", "dto", "api", "index", "token", "json", "http", "llm", "scope",
    ];

    public static IReadOnlyList<HelpTopic> All { get; } =
    [
        new("home.folders", "Your folders",
            "The four folders DeskAI can work in: your Desktop, Downloads, Documents, and Pictures.",
            "Press Connect and DeskAI remembers the names, sizes, and dates of what is inside, then opens it in Organize, which asks your permission before anything moves. You can disconnect a folder on Search at any time.",
            "It never touches anything outside these four folders, and nothing moves until you press Tidy."),
        new("home.ask", "Ask DeskAI",
            "A box where you ask about your connected folders in your own words, helped by the AI you set up.",
            "DeskAI asks once before the first question, then sends only your words. The AI says what kind of question it is; DeskAI looks in what it remembers and answers, with a button to open Search or Organize.",
            "It never sends file names, folder names, or anything about your files, and never moves or changes anything."),
        new("home.health", "Organization score",
            "A score out of 100 for how settled your connected folders look.",
            "It adds up two things shown below it: space that might be taken by copies, and files nobody has changed in about six months. Each part shows how much it counted.",
            "It never changes, moves, or deletes anything. It only describes."),
        new("home.duplicates", "Possible duplicates",
            "Files that are exactly the same size, so they might be copies of each other.",
            "DeskAI groups them so you can look at them. The same size is a hint, not proof, until you ask DeskAI to compare them.",
            "It never deletes a copy. Nothing here changes your files."),
        new("home.copyCheck", "Checking for real copies",
            "A way to find out which possible copies are really the same file.",
            "After you agree, DeskAI reads the listed files on this computer and compares them. It tells you which are identical and which only share a size.",
            "It never deletes, moves, saves, or sends anything it reads."),
        new("home.storage", "Where your space is going",
            "A breakdown of how much space each kind of file uses in your connected folders.",
            "It shows totals for documents, pictures, videos, and more, plus your largest files, from what DeskAI remembered the last time it looked.",
            "It never opens, moves, or deletes files. Refresh a folder in Search to update it."),
        new("organize.tidy", "Tidying a folder",
            "A way to sort the loose files in one of your folders into neat folders inside it.",
            "Pick a folder and DeskAI suggests where each loose file belongs, like PDFs into Documents. Untick anything you want to keep where it is.",
            "Nothing moves until you press Tidy, and you can undo it. It never deletes anything or moves files out of the folder you picked."),
        new("organize.permission", "Permission to tidy",
            "Your yes, for one folder, that DeskAI may tidy it.",
            "Without it, DeskAI can only look. You can take it back at any time, and the folder stays connected for searching.",
            "It never lets DeskAI delete files, touch files in subfolders, or move anything out of the folder."),
        new("organize.suggestions", "Where suggestions come from",
            "How DeskAI decides where each file should go.",
            "It looks at the kind of file, such as PDF or photo. If one of your rules matches a file, your rule wins. If you ask, AI can suggest a place too. Each file shows which one decided.",
            "Suggestions never move anything by themselves."),
        new("organize.askAi", "Asking AI",
            "A way to get ideas from the AI you set up about where some files belong.",
            "Before anything is sent, DeskAI shows exactly what the AI would see, such as file types, and you press Send. Ideas the AI is unsure about start unticked.",
            "It never sends what is inside your files or where they are, and AI never moves anything or picks a folder outside this one."),
        new("organize.planAi", "Planning a folder with AI",
            "A way to have the AI you set up suggest folders for this whole folder and where each file goes.",
            "DeskAI shows exactly what the AI would see first, then you press Send. The AI's folder names and choices appear as the usual preview, grouped by folder, for you to tick or untick before Tidy.",
            "DeskAI checks every folder name and only ever makes folders inside this one. Nothing moves until you press Tidy, and you can undo it."),
        new("organize.undo", "Undo",
            "A way to put back the files your last tidy moved, even after DeskAI was closed.",
            "Each file goes back only if it has not changed since and its old spot is free. Folders DeskAI made are removed once they are empty.",
            "It never replaces a file, and never removes a folder you had before or one with anything in it."),
        new("organize.interrupted", "An interrupted tidy",
            "A tidy that stopped part-way, for example because the computer turned off.",
            "DeskAI checks each file that was moving and tells you how many moved. You can put those back or keep them.",
            "It never guesses. A file it cannot be sure about is left alone for you to check."),
        new("organize.leftAlone", "Left alone",
            "Files DeskAI decided not to touch, each with its reason.",
            "For example files still downloading, changed in the last few minutes, stored online only, hidden, or of a kind DeskAI does not know.",
            "Files listed here are never moved."),
        new("search.searching", "Searching",
            "A way to find files in the folders you connected by typing what you want.",
            "Type something like \"photos from last month\" or \"documents over 10 mb\". DeskAI shows how it read your words, then lists the files that match.",
            "Searching never moves or renames a file. It opens supported content only after that folder's separate reading permission."),
        new("search.askAi", "Letting AI read your search",
            "A way to have the AI you set up turn your own words into a search DeskAI understands.",
            "Only the words you typed are sent, after you see them in a dialog and press Send. The AI's reading appears in the box as a plain search you can change, and DeskAI runs that.",
            "It never sends file names, folder names, or anything about your files, and never opens or moves anything."),
        new("studio.groups", "Find groups",
            "A board that shows the folders and files on your Desktop sorted into groups.",
            "With AI, DeskAI first shows exactly what the AI will see, then sorts by its answer. Without AI, DeskAI guesses from the kinds of files. You can rename, merge, and move groups.",
            "It never moves, renames, or opens your files, and never changes Windows."),
        new("studio.oldStuff", "Clear old stuff",
            "A card that gathers what you haven't changed in 6 months into one Old stuff folder on your Desktop.",
            "DeskAI lists each old folder and file with a tick box first. Only what you tick moves, after you press Move. Put back returns your latest change.",
            "It never deletes anything and never moves anything off your Desktop. Projects and programs start unticked."),
        new("studio.folderByGroup", "Putting groups in folders",
            "The step after Find groups: a folder on your Desktop for each group, with the group's things inside.",
            "DeskAI lists what would go into which folder first. Only what you tick moves, after you press Move. Not sure stays where it is, and Put back returns your latest change.",
            "It never deletes anything, asks no AI when moving, and never moves anything off your Desktop."),
        new("studio.tagNames", "Adding group names to folders",
            "The step after Find groups that puts each group's name in front of its folders' names.",
            "DeskAI lists each folder and its new name first. Only what you tick is renamed, after you press Rename. Files keep their names, and Put back returns your latest change.",
            "It never deletes anything, never renames files, and asks no AI when renaming."),
        new("search.connect", "Connecting a folder",
            "Giving DeskAI permission to look at one folder you choose.",
            "DeskAI remembers the names, sizes, and dates of the files in it so you can search them. Disconnect it at any time and DeskAI forgets everything about it.",
            "Connecting never lets DeskAI move, rename, or delete anything."),
        new("search.readInside", "Reading inside files",
            "Extra permissions for one folder to search words inside supported files.",
            "Search can read notes and modern Word and Excel files. Separate choices allow PDF text and modern PowerPoint slide text. Results show a short matching piece and a slide number when available.",
            "These permissions do not open pictures or scanned pages. Extracted words are not saved or sent to AI."),
        new("search.saved", "Saved searches",
            "A search you gave a name so you can run it again with one click.",
            "Running it searches again from scratch in the folders connected right now, so the results are always up to date.",
            "A saved search is not a folder. It never moves or copies files."),
        new("automation.askAi", "Letting AI read your sentence",
            "A way to have the AI you set up turn your own words into a rule DeskAI understands.",
            "Only the words you typed are sent, after you see them in a dialog and press Send. The AI's reading appears in the boxes below as a draft you can change. Nothing is saved until you press Add.",
            "It never sends anything about your files, and a rule it drafts can only move files into a folder inside the one you chose."),
        new("automation.checking", "Checking for you",
            "DeskAI looking at your connected folders by itself.",
            "Every so often it checks whether any file matches your rules, and tells you if something does.",
            "It never moves a file on its own, except where you turned on Tidy while I'm away, and never adds itself to Windows startup."),
        new("automation.frequency", "How often",
            "How often DeskAI looks at your connected folders while it is open.",
            "Pick every 15 minutes, every hour, a few times a day, or only when you press Check now.",
            "Looking more often never makes DeskAI change anything."),
        new("automation.pause", "Pause",
            "An off switch for automatic checks.",
            "Turn it on and DeskAI stops looking by itself straight away, even in the middle of a check.",
            "Pausing never deletes your rules or your history."),
        new("automation.notifications", "Windows notifications",
            "An optional message from Windows when a check finds something.",
            "It says how many files matched. It is off unless you turn it on; while it is off, DeskAI shows a quiet note inside the app instead.",
            "It never shows file names, so nobody looking at your screen sees them."),
        new("automation.keeprunning", "Keep running after you close it",
            "DeskAI staying near the clock and carrying on checking after you close its window.",
            "Turning it on is what puts DeskAI near the clock; click the arrow there to show hidden icons if you cannot see it. Right-click the icon to open DeskAI, pause checking, or quit.",
            "It never adds itself to Windows startup, and it moves nothing on its own outside a folder where you turned on Tidy while I'm away."),
        new("organize.away", "Tidy while I'm away",
            "Your yes, for one folder, that DeskAI may move what your rules match while you are not watching.",
            "Each time DeskAI checks, it moves loose files here that your switched-on rules match, at most 25 at a time. It stops and waits for you if a rule changes or a file is in the way.",
            "It never deletes anything, never moves a file out of this folder, and never touches a file your rules don't name."),
        new("automation.rules", "Rules",
            "Instructions you write for a tidy-up you do again and again.",
            "For example: when a file name contains \"invoice\", it belongs in Sorted. You can turn a rule off or delete it at any time.",
            "Saving a rule never moves anything by itself."),
        new("automation.practice", "Practice run",
            "A preview of exactly what your rules would do right now.",
            "It lists each file that would move and where it would go, plus any files your rules disagree about, which are left alone.",
            "A practice run never moves anything."),
        new("automation.sentence", "Writing a rule in your own words",
            "A shortcut for filling in the rule form.",
            "Type something like \"move invoices to Documents\" and DeskAI fills in the boxes below. Check them, give the rule a name, and save it.",
            "It never saves a rule for you. It only fills in the boxes."),
        new("workspace.page", "My workspace",
            "A page for your pinned searches and ready-made starter packs.",
            "Pin the searches you use most to see how many files each finds at a glance, or add a starter pack of searches and rules for how you use your computer.",
            "Nothing on this page moves, renames, opens, or deletes a file."),
        new("workspace.pins", "Pinned searches",
            "Saved searches you chose to keep on this page, up to eight.",
            "Each one shows how many files it finds in your connected folders, from what DeskAI remembers. Open in Search shows the files themselves.",
            "A pin never moves or copies files. It only counts them."),
        new("workspace.packs", "Starter packs",
            "Ready-made saved searches and rules for students, gamers, and other kinds of people.",
            "Pick one to see exactly what it adds before anything is added. Anything you already have is skipped, and you can change or remove what it adds later.",
            "Rules from a pack start switched off. Nothing moves until you turn a rule on and press Tidy."),
        new("workspace.look", "DeskAI's look",
            "How DeskAI's own window looks: its colours, and whether it is light or dark.",
            "Pick a look and choose light, dark, or follow Windows. It changes only the DeskAI window, straight away, and is remembered next time.",
            "It never changes your Windows theme, wallpaper, or any file. Green always means DeskAI is allowed to do something."),
        new("workspace.wallpaper", "Wallpaper",
            "A way to make a picture you pick your Windows wallpaper, and to put the old one back.",
            "Choose a picture from your computer, see it, and press the button. DeskAI remembers the wallpaper you had, so one press puts it back, even after DeskAI was closed.",
            "It never looks through your folders for pictures, never makes or downloads a picture, and changes no other Windows setting."),
        new("workspace.folders", "Your folders",
            "The four folders DeskAI can work in: your Desktop, Downloads, Documents, and Pictures.",
            "Press Connect and DeskAI remembers the names, sizes, and dates of what is inside, then opens it in Organize, which asks your permission before anything moves. A folder inside one of the four can be chosen on Organize or Search.",
            "It never touches anything outside these four folders, and nothing moves until you press Tidy."),
        new("workspace.templates", "Folder templates",
            "A set of empty folders, made inside a folder you chose, so it is ready to be tidied into.",
            "Pick a template or type your own names. You see the exact list first, and DeskAI needs your permission to tidy that folder. Undo removes only empty folders. In a synced folder, new folders reach your other devices too.",
            "It never moves, renames, or deletes a file, and never makes folders anywhere else."),
        new("settings.sharing", "What online AI may see",
            "Your choice of what information about your files may be sent to online AI.",
            "Switch on only what you are happy to share, such as file types. It matters only if you turn on online AI below.",
            "Private and protected files are always left out. What is written inside your files is never sent."),
        new("settings.aiChoice", "Choosing how AI works",
            "Whether DeskAI uses AI at all, and where that AI runs.",
            "Choose no AI, AI running on this computer, or an online AI service with your own key. AI only ever gives ideas.",
            "If your choice stops working, DeskAI never quietly switches to a different service."),
        new("settings.key", "Your key",
            "The password-like code an online AI service gave you, so DeskAI can use your account.",
            "Windows keeps it safe. DeskAI uses it only for the service you picked, and only when you ask for AI ideas.",
            "DeskAI never shows your key again and never sends it to a different company."),
        new("settings.dailyLimit", "Daily limit",
            "The most online AI requests DeskAI may make in one day.",
            "Once it is reached, DeskAI stops asking the AI service until tomorrow. Each time you ask AI for ideas counts as one request.",
            "DeskAI never retries by itself, so it cannot use up requests without you."),
        new("settings.backup", "Backing up and restoring",
            "A file holding your rules and saved searches, so you can bring them back or move them to another computer.",
            "Save writes the file where you choose. Restore shows what the file would add before adding it, and skips anything you already have.",
            "The file never holds your folders, your keys, or where your files are. Restored rules start switched off."),
        new("settings.freshStart", "Starting fresh",
            "A way to make DeskAI forget everything it remembers, as if you had just installed it.",
            "After you agree, DeskAI forgets your connected folders, rules, saved searches, AI choice, keys, and history. Do this before removing DeskAI.",
            "It never moves or deletes a file. Anything DeskAI tidied stays where it is."),
        new("shell.scope", "What DeskAI can see",
            "A reminder of which of your folders DeskAI is allowed to look at right now.",
            "It counts the folders you connected and the files DeskAI remembers, and says if you let it read inside or tidy any of them.",
            "DeskAI never looks anywhere you have not chosen."),
    ];

    public static HelpTopic? Find(string? id) =>
        string.IsNullOrWhiteSpace(id)
            ? null
            : All.FirstOrDefault(topic => string.Equals(topic.Id, id, StringComparison.Ordinal));
}
