using System.Diagnostics;
using System.Runtime.InteropServices;
using DeskAI.IconProbe;

// ADR 0043. Refuse first: nothing below may run outside Windows Sandbox.
if (SandboxGuard.Check(Environment.UserName) is { } refusal)
{
    Console.Error.WriteLine(refusal);
    return 2;
}

var results = args.Length == 1 ? args[0] : throw new ArgumentException("Usage: IconPositionProbe <results folder>");
var report = new ProbeReport();
var clock = TimeProvider.System;
var wait = TimeSpan.FromSeconds(60);
var step = TimeSpan.FromMilliseconds(500);

var desktop = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);
var names = Enumerable.Range(1, 12).Select(i => $"deskai-probe-{i:D2}.txt").ToList();
foreach (var name in names)
{
    File.WriteAllText(Path.Combine(desktop, name), "Generated by the DeskAI icon-position probe.");
}

var view = await Waiting.ForAsync(
    () => DesktopShellView.TryOpen() is { } v && names.All(v.ReadPositions().ContainsKey) ? v : null, wait, step, clock);
if (view is null)
{
    report.Add(new Stage("find desktop view", StageOutcome.Failed, "Explorer did not show the probe's icons within 60 seconds"));
    return Finish(3);
}

report.Note($"windows: {Environment.OSVersion.VersionString}");
report.Note($"dpi: {GetDpiForSystem()}");
report.Note($"icon spacing: {view.Spacing.X} x {view.Spacing.Y}");
var area = WorkArea();
report.Note($"work area: {area.Left},{area.Top} - {area.Right},{area.Bottom}");

var originalFlags = view.ReadFlags();
var originalPositions = view.ReadPositions();
report.Note($"auto arrange at start: {(originalFlags & DesktopShellView.AutoArrange) != 0}");
report.Note($"icons at start: {originalPositions.Count}");

// Place.
view.WriteFlags(DesktopShellView.AutoArrange | DesktopShellView.SnapToGrid, 0);
var targets = names.Zip(ProbeLayout.Targets(names.Count, view.Spacing, area)).ToDictionary(p => p.First, p => p.Second);
view.Place(targets);
await Task.Delay(TimeSpan.FromSeconds(2));
Record("place", PositionCheck.Differences(targets, view.ReadPositions(), view.Spacing));

// Refresh.
view.Refresh();
await Task.Delay(TimeSpan.FromSeconds(3));
Record("refresh", PositionCheck.Differences(targets, view.ReadPositions(), view.Spacing));

// Explorer restart: recorded for the owner, not required (ADR 0043).
view.Dispose();
foreach (var explorer in Process.GetProcessesByName("explorer"))
{
    explorer.Kill();
}

Process.Start(new ProcessStartInfo("explorer.exe") { UseShellExecute = true });
view = await Waiting.ForAsync(
    () => DesktopShellView.TryOpen() is { } v && names.All(v.ReadPositions().ContainsKey) ? v : null, wait, step, clock);
if (view is null)
{
    report.Add(new Stage("explorer restart", StageOutcome.Failed, "Explorer did not come back within 60 seconds"));
    report.Add(new Stage("put back", StageOutcome.Skipped, "no desktop view"));
    return Finish(1);
}

await Task.Delay(TimeSpan.FromSeconds(3));
Record("explorer restart", PositionCheck.Differences(targets, view.ReadPositions(), view.Spacing));

// Put back: every original position, then the original flags.
view.Place(originalPositions);
view.WriteFlags(DesktopShellView.AutoArrange | DesktopShellView.SnapToGrid, originalFlags);
await Task.Delay(TimeSpan.FromSeconds(2));
var putBack = PositionCheck.Differences(originalPositions, view.ReadPositions(), view.Spacing).ToList();
if ((view.ReadFlags() & (DesktopShellView.AutoArrange | DesktopShellView.SnapToGrid))
    != (originalFlags & (DesktopShellView.AutoArrange | DesktopShellView.SnapToGrid)))
{
    putBack.Add("auto arrange / snap to grid not restored");
}

Record("put back", putBack);
view.Dispose();
return Finish(report.IsReliable ? 0 : 1);

void Record(string stage, IReadOnlyList<string> differences) =>
    report.Add(differences.Count == 0
        ? new Stage(stage, StageOutcome.Passed, string.Empty)
        : new Stage(stage, StageOutcome.Failed, string.Join("; ", differences)));

int Finish(int code)
{
    Directory.CreateDirectory(results);
    File.WriteAllText(Path.Combine(results, "report.txt"), report.Render());
    Console.WriteLine(report.Render());
    return code;
}

static Rect WorkArea()
{
    var rect = new int[4];
    return SystemParametersInfo(0x0030 /* SPI_GETWORKAREA */, 0, rect, 0)
        ? new Rect(rect[0], rect[1], rect[2], rect[3])
        : throw new InvalidOperationException("Windows did not give the work area.");
}

[DllImport("user32.dll", SetLastError = true)]
[return: MarshalAs(UnmanagedType.Bool)]
static extern bool SystemParametersInfo(uint action, uint parameter, [Out] int[] value, uint flags);

[DllImport("user32.dll")]
static extern uint GetDpiForSystem();
