<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DeskAI.AI\DeskAI.AI.csproj" />
    <ProjectReference Include="..\..\src\DeskAI.Core\DeskAI.Core.csproj" />
  </ItemGroup>
</Project>
